name: app
description: Your personal prophet
author: Igor Ianishevskyi
homepage: prophet.ninja

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  flutter_bloc: ^4.0.0
  flutter_bloc_stream: ^3.0.0
  equatable: ^1.1.1
  easy_localization: ^2.2.1
  to_string: ^1.2.1
  # Firebase
  firebase_core: ^0.4.4+3
  firebase_analytics: ^5.0.11
  # cloud_firestore: ^0.12.9+5 # disabled

  prophecy_model:
    path: ../models/prophecy_model
  user_model:
    path: ../models/user_model 
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.9.0
  built_value: ^7.1.0
  to_string_generator: ^1.2.1

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/data/prophecies.json
