name: app
description: Your personal prophet
author: Igor Ianishevskyi
homepage: prophet.ninja

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  provider: ^4.2.0
  flutter_bloc: ^4.0.0
  url_launcher: ^5.5.0
  mutable_wrappers: ^1.0.0

  #models
  prophecy_model:
    path: ../models/prophecy_model
  user_model:
    path: ../models/user_model 
  
  #data
  users:
    path: ../data/abstract/users
  auth:
    path: ../data/abstract/auth
  prophecies:
    path: ../data/abstract/prophecies
  auth_flutter:
    path: ../data/platform/auth_flutter  
  prophecies_flutter:
    path: ../data/platform/prophecies_flutter  
 
  #blocs
  authentication:
    path: ../blocs/authentication
  prophecy:
    path: ../blocs/prophecy

  #localization
  language:
    path: ../language
  
  #widgets
  cupertino_icons: ^0.1.2
  
dev_dependencies:
  #flutter_test:
    #sdk: flutter
  flutter_launcher_icons: "^0.7.0"

flutter_icons:
  ios: true
  android: true
  image_path_ios: "assets/launcher/icon.png"
  image_path_android: "assets/launcher/icon.png"


flutter:
  uses-material-design: true
  assets:
    - assets/background.jpg
    - assets/launcher/icon.png
  #data
    - packages/prophecies_flutter/data/prophecies.json
  # #localization
    # - packages/language/locales/ru.json
