name: my_prophet
description: Your personal prophet
author: Igor Ianishevskyi
homepage: prophet.ninja
publish_to: none

version: 0.1.0

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # flutter mobile app stuff
  flutter_bloc: 
  url_launcher: 
  launch_review: 
  mutable_wrappers: 
  flutter_svg: 
  flutter_spinkit:

  # base
  base:
    path: ../base
  text:
    path: ../text
  algorithm:
    path: ../algorithm
  # network
  firebase_core:
  firebase_analytics:
  firebase_crashlytics:
  firebase_in_app_messaging: 
  firebase_messaging:
  google_mobile_ads:
  flutter_local_notifications:
  timezone: 
  flutter_native_timezone: 


dev_dependencies:
  #flutter_test:
    #sdk: flutter
  flutter_launcher_icons:
  flutter_native_splash:

flutter_icons:
  ios: true
  android: true
  image_path_ios: "assets/launcher/icon-ios.png"
  image_path_android: "assets/launcher/icon-android.png"
  adaptive_icon_background: "assets/launcher/icon-android-background.png"
  adaptive_icon_foreground: "assets/launcher/icon-android-foreground.png"

flutter_native_splash:
  image: "assets/splash.png"
  background_image: "assets/background.jpg"

flutter:
  uses-material-design: true
  assets:
    - assets/background.jpg
    - assets/splash.png
    - assets/icons/
    - assets/widget/
    - assets/card/
  #data
    # - packages/prophecies_repository_flutter/data/prophecies.json
  # #localization
    # - packages/language/locales/ru.json
