name: my_prophet
description: Your personal prophet
homepage: prophet.ninja
publish_to: none

version: 0.1.1

environment:
  sdk: ">=2.11.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # basic modules
  base:
    path: ../base
  text:
    path: ../text
  algorithm:
    path: ../algorithm
  symbol:
    path: ../symbol

  # needed for models
  flutter_bloc: ^7.1.0
  mutable_wrappers: ^1.0.0

  # assets
  flutter_svg: ^0.22.0
  jovial_svg: ^1.0.6

  # animation
  flutter_spinkit: ^5.0.0
  proste_route_animation: ^2.0.2

  # services
  url_launcher: ^6.0.9
  launch_review: ^3.0.1
  flutter_dotenv: ^5.0.0
  flutter_local_notifications: ^8.1.1
  timezone: ^0.7.0
  flutter_native_timezone: ^2.0.0
  
  # network
  firebase_core: ^1.4.0
  firebase_analytics: ^8.2.0
  firebase_crashlytics: ^2.1.1
  google_mobile_ads: ^0.13.3

  # not used
  firebase_in_app_messaging: any 
  firebase_messaging: any


dev_dependencies:
  #flutter_test:
    #sdk: flutter
  flutter_launcher_icons:
  flutter_native_splash:

flutter_icons:
  ios: true
  android: true
  image_path_ios: "assets/launcher/icon-ios.png"
  image_path_android: "assets/launcher/icon-android.png"
  adaptive_icon_background: "assets/launcher/icon-android-background.png"
  adaptive_icon_foreground: "assets/launcher/icon-android-foreground.png"

flutter_native_splash:
  image: "assets/splash.png"
  background_image: "assets/background.png"

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/background.png
    - assets/splash.png
    - assets/icons/
    - assets/widget/
    - assets/card/card_placeholder.png
    - assets/card/card_text.png
    - assets/card/si/
    - assets/gem/
    - assets/numerology/si/
    - assets/tarrot/
