name: user_model
description: user_model
author: bgoncharuck
version: 0.0.1+1

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  meta: ^1.1.8
  json_annotation: ^3.0.1
  
dev_dependencies:
  build_runner: ^1.0.0
  json_serializable: ^3.2.0
