name: int_datetime
description: a use of DateTime classs as an integer and other usefull and needed features that I must cut from my_prophet to seperate library.
version: 0.0.1
license: LGPL v2
homepage: https://github.com/bgoncharuck/int_datetime

environment:
  sdk: ">=2.6.0 <3.0.0"
  
dependencies:
