name: authentication
description: authentication
author: bgoncharuck
version: 0.0.1+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  meta: ^1.1.8
  bloc: ^4.0.0
  equatable: ^1.2.0
  to_string: ^1.2.1

  users_repository:
    path: ../../data/abstract/users_repository
  auth:
    path: ../../data/abstract/auth
  user_model:
    path: ../../models/user_model

dev_dependencies:
  build_runner: ^1.0.0
  to_string_generator: ^1.2.1
